version: "3.10"

services:
  pg:
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - backend

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER" ]
      interval: 30s
      timeout: 60s
      retries: 5


  gunicorn-backend:
    env_file:
      - .env
    build: .
    ports:
      - "8000:8000"
    depends_on:
      pg:
        condition: service_healthy
    command: bash -c "
      flask db upgrade
      && pip install gunicorn
      && gunicorn wsgi:app -b 0.0.0.0
      "
    networks:
      - backend

  prod-backend:
    env_file:
      - .env
    build: .
    ports:
      - "9000:80"
    depends_on:
      pg:
        condition: service_healthy
    command: bash -c "
      flask db upgrade && 
      flask run --host=0.0.0.0 --port=80
      "
    networks:
      - backend
#    environment:
#      FLASK_APP: main.py

networks:
  backend: