version: "3.10"

services:
  pg:
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - backend

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER" ]
      interval: 30s
      timeout: 60s
      retries: 5

#  dev-backend:
#    env_file:
#      - .env
#    build: .
#    ports:
#      - "5000:5000"
#    depends_on:
#      pg:
#        condition: service_healthy
#    command: bash -c "
#      python main.py
#      "
#    networks:
#      - backend

networks:
  backend: