"""empty message

Revision ID: 485db2325f02
Revises: d6a24be0e576
Create Date: 2024-06-09 23:19:28.853067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '485db2325f02'
down_revision = 'd6a24be0e576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_username_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('users_username_key', ['username'])

    # ### end Alembic commands ###
