"""empty message

Revision ID: 58aa1e86dd89
Revises: 1148cc31a21b
Create Date: 2024-06-14 22:04:53.764913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58aa1e86dd89'
down_revision = '1148cc31a21b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('notification',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('notification',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
